# -*- coding: utf-8 -*-
"""bcg_chatbot.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1TsXrGBOQW_RqMd7-twdAgppZ-mrBZ8P7
"""

"""
SEC EDGAR XBRL API — Extract Key Financials for Multiple Companies
Fetches: Total Revenue, Net Income, Total Assets, Total Liabilities,
         Cash Flow from Operating Activities
"""

import requests
import json
from datetime import datetime

# ── Companies to fetch ─────────────────────────────────────────────────────────
# Add or remove companies here. CIKs must be zero-padded to 10 digits.
# Look up any company's CIK at: https://www.sec.gov/cgi-bin/browse-edgar?action=getcompany
COMPANIES = [
    {"name": "Microsoft", "cik": "0000789019"},
    {"name": "Apple",     "cik": "0000320193"},
    {"name": "Tesla",     "cik": "0001318605"},
]

FISCAL_YEAR = "FY"   # Annual filings only (not quarterly)
NUM_YEARS   = 3      # How many recent years to display

# SEC EDGAR requires a descriptive User-Agent header
HEADERS = {
    "User-Agent": "financial-research-script anthonymai14@gmail.com"
}

# ── XBRL concept tags for each metric ──────────────────────────────────────────
# Companies may use slightly different tags; we try multiple fallbacks in order
METRICS = {
    "Total Revenue": [
        "RevenueFromContractWithCustomerExcludingAssessedTax",
        "Revenues",
        "SalesRevenueNet",
        "RevenueFromContractWithCustomerIncludingAssessedTax",
    ],
    "Net Income": [
        "NetIncomeLoss",
        "NetIncome",
        "ProfitLoss",
    ],
    "Total Assets": [
        "Assets",
    ],
    "Total Liabilities": [
        "Liabilities",
    ],
    "Cash Flow from Operations": [
        "NetCashProvidedByUsedInOperatingActivities",
    ],
}


# ── Helpers ────────────────────────────────────────────────────────────────────

def fetch_company_facts(cik: str) -> dict:
    url = f"https://data.sec.gov/api/xbrl/companyfacts/CIK{cik}.json"
    response = requests.get(url, headers=HEADERS, timeout=15)
    response.raise_for_status()
    return response.json()


def extract_annual_values(facts: dict, concept_tags: list) -> dict:
    """Try each fallback tag and return deduplicated annual (10-K) data points."""
    us_gaap = facts.get("facts", {}).get("us-gaap", {})

    for tag in concept_tags:
        if tag not in us_gaap:
            continue
        usd_data = us_gaap[tag].get("units", {}).get("USD", [])

        # Keep only annual 10-K filings
        annual = [
            e for e in usd_data
            if e.get("form") == "10-K" and e.get("fp") == FISCAL_YEAR
        ]
        if not annual:
            continue

        # Deduplicate: keep the latest-filed entry per fiscal year-end date
        by_year = {}
        for e in annual:
            end, filed = e["end"], e.get("filed", "")
            if end not in by_year or filed > by_year[end]["filed"]:
                by_year[end] = e

        return {
            "tag_used": tag,
            "data": {k: v["val"] for k, v in sorted(by_year.items(), reverse=True)},
        }

    return {"tag_used": None, "data": {}}


def format_value(val) -> str:
    """Format a dollar value in billions, or return 'N/A'."""
    if val is None:
        return "N/A"
    return f"${val / 1_000_000_000:,.2f}B"


def print_company_table(entity_name: str, results: dict):
    """Print a formatted table for one company."""
    all_dates = set()
    for r in results.values():
        all_dates.update(r["data"].keys())
    recent_dates = sorted(all_dates, reverse=True)[:NUM_YEARS]

    col_w = 14
    divider = "=" * (32 + col_w * len(recent_dates))

    print(f"\n{divider}")
    print(f"  {entity_name}")
    print(divider)

    header = f"{'Metric':<32}" + "".join(d[:4].rjust(col_w) for d in recent_dates)
    print(header)
    print("-" * len(header))

    for metric_name, result in results.items():
        row = f"{metric_name:<32}"
        for date in recent_dates:
            row += format_value(result["data"].get(date)).rjust(col_w)
        print(row)

    print(divider)


# ── Main ───────────────────────────────────────────────────────────────────────

# def main():
#     print(f"\nSEC EDGAR Financial Comparison  |  Generated {datetime.today().strftime('%Y-%m-%d')}")
#     print(f"Source: https://data.sec.gov/api/xbrl/companyfacts/")

#     all_data = {}   # Stores results for optional JSON export

#     for company in COMPANIES:
#         name, cik = company["name"], company["cik"]
#         #print(f"\n  Fetching {name} (CIK {cik})...", end=" ", flush=True)

#         try:
#             facts = fetch_company_facts(cik)
#             entity_name = facts.get("entityName", name)

#             results = {
#                 metric: extract_annual_values(facts, tags)
#                 for metric, tags in METRICS.items()
#             }

#             #print("done.")
#             print_company_table(entity_name, results)
#             all_data[entity_name] = results

#         except Exception as e:
#             print(f"ERROR — {e}")




# if __name__ == "__main__":
#     main()

import pandas as pd

def main():
    all_rows = []

    for company in COMPANIES:
        name, cik = company["name"], company["cik"]
        print(f"Fetching {name}...", end=" ", flush=True)

        try:
            facts = fetch_company_facts(cik)
            entity_name = facts.get("entityName", name)

            results = {
                metric: extract_annual_values(facts, tags)
                for metric, tags in METRICS.items()
            }

            # Collect recent fiscal year-end dates
            all_dates = set()
            for r in results.values():
                all_dates.update(r["data"].keys())
            recent_dates = sorted(all_dates, reverse=True)[:NUM_YEARS]

            # Build one row per year
            for date in recent_dates:
                row = {"Company": entity_name, "Fiscal Year End": date, "Year": int(date[:4])}
                for metric, result in results.items():
                    val = result["data"].get(date)
                    row[metric] = val / 1_000_000_000 if val is not None else None  # convert to $B
                all_rows.append(row)

            print("done.")

        except Exception as e:
            print(f"ERROR — {e}")

    # Build DataFrame
    df = pd.DataFrame(all_rows)
    df = df.sort_values(["Company", "Year"], ascending=[True, False]).reset_index(drop=True)

    # Format dollar columns to 2 decimal places (in $B)
    metric_cols = list(METRICS.keys())
    df[metric_cols] = df[metric_cols].round(2)

    return df


df = main()

df

from google.colab import files

df.to_csv("financials.csv", index=False)
files.download("financials.csv")

df['Revenue Growth (%)'] = df.groupby(['Company'])['Total Revenue'].pct_change() * 100
df['Net Income Growth (%)'] = df.groupby(['Company'])['Net Income'].pct_change() * 100

df

